name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: skillforge-backend
          IMAGE_TAG: ${{ github.sha }}

        run: |
          cd Backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Get Github Runner IP
        id: ip
        run: |
          echo "ipv4=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Whitelist Runner IP in Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id sg-01edcb78ff8ce5521 \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Get ECR Login Token
        id: ecr-token
        run: |
          echo "token=$(aws ecr get-login-password --region ap-south-1)" >> $GITHUB_OUTPUT

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3

        env:
          IMAGE_TAG: ${{ github.sha }}
          ECR_TOKEN: ${{ steps.ecr-token.outputs.token }}

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_TAG,ECR_TOKEN
          timeout: 60s
          command_timeout: 20m
          script_stop: true

          script: |
            set -e

            # Login to ECR using forwarded token
            echo "$ECR_TOKEN" | docker login --username AWS --password-stdin 312957453068.dkr.ecr.ap-south-1.amazonaws.com

            cd /home/ubuntu/app

            # Pull latest backend image
            docker compose pull backend

            # Recreate container with new image
            docker compose up -d --force-recreate backend

            # Wait and verify it started
            sleep 5
            docker ps | grep skillforge_backend

            echo "✅ Deployment complete!"

      - name: Revoke Runner IP from Security Group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id sg-01edcb78ff8ce5521 \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32